using System.Runtime.Versioning;
using Microsoft.Win32;

namespace OutlookScraper.App.Notifications;

/// <summary>
/// Best-effort reporting on the shell registration that unpackaged toasts depend on.
/// </summary>
/// <remarks>
/// Advisory only, and deliberately so.
///
/// An unpackaged app needs a Start Menu shortcut carrying an AppUserModelID and a
/// registered COM activator before Windows will show it a toast, and when they are
/// missing Windows fails silently — no toast, no error. That is worth surfacing.
///
/// But the notification compat layer <b>derives its own AUMID</b> and creates the
/// registration lazily, so "nothing found" before the first toast is the normal state
/// on a fresh install, not a fault. An earlier version of this class invented its own
/// AUMID constant and asserted the registry must contain it; that key is never written
/// by anyone, so the check always failed and — worse — it was used to gate the
/// "send test notification" button, which meant the diagnostic built to prove toasts
/// worked was the thing preventing them from being tried.
///
/// Hence: report, never gate.
/// </remarks>
[SupportedOSPlatform("windows")]
public static class ToastRegistration
{
    private const string ClassesRoot = @"SOFTWARE\Classes";

    /// <summary>
    /// A human-readable description of what is currently registered, for logs and the
    /// settings screen. Never throws.
    /// </summary>
    public static string Describe()
    {
        var currentPath = Environment.ProcessPath;

        if (string.IsNullOrEmpty(currentPath))
        {
            return "Could not determine the running executable's path.";
        }

        try
        {
            var registeredPath = FindRegisteredServerPath();

            if (registeredPath is null)
            {
                return "No toast COM activator is registered yet. This is normal before " +
                       "the first notification — the notification layer registers itself " +
                       "on first use.";
            }

            return registeredPath.Contains(currentPath, StringComparison.OrdinalIgnoreCase)
                ? "Toast activator is registered for this executable."
                : $"Toast activator is registered for '{registeredPath}', but this copy is " +
                  $"running from '{currentPath}'. Moving or renaming the executable breaks " +
                  "notifications silently; sending a test notification re-registers it.";
        }
        catch (Exception ex) when (ex is System.Security.SecurityException or UnauthorizedAccessException)
        {
            return "Could not read the toast registration: " + ex.Message;
        }
    }

    /// <summary>
    /// True only when an activator is registered and points somewhere other than this
    /// executable — the one case genuinely worth warning about, because it is the
    /// silent-failure mode after the app is moved.
    /// </summary>
    public static bool LooksStale(out string detail)
    {
        detail = Describe();

        var currentPath = Environment.ProcessPath;

        if (string.IsNullOrEmpty(currentPath))
        {
            return false;
        }

        try
        {
            var registeredPath = FindRegisteredServerPath();

            return registeredPath is not null &&
                   !registeredPath.Contains(currentPath, StringComparison.OrdinalIgnoreCase);
        }
        catch (Exception ex) when (ex is System.Security.SecurityException or UnauthorizedAccessException)
        {
            return false;
        }
    }

    /// <summary>
    /// Walks the registered CLSIDs looking for a LocalServer32 pointing at this app.
    /// The activator GUID is generated by the notification layer, so it has to be found
    /// rather than assumed — which is precisely the mistake the old AUMID check made.
    /// </summary>
    private static string? FindRegisteredServerPath()
    {
        using var clsidRoot = Registry.CurrentUser.OpenSubKey($@"{ClassesRoot}\CLSID");

        if (clsidRoot is null)
        {
            return null;
        }

        foreach (var clsid in clsidRoot.GetSubKeyNames())
        {
            using var server = clsidRoot.OpenSubKey($@"{clsid}\LocalServer32");

            if (server?.GetValue(null) is string path &&
                path.Contains("OutlookScraper", StringComparison.OrdinalIgnoreCase))
            {
                return path;
            }
        }

        return null;
    }
}
