using System.Runtime.Versioning;
using Microsoft.Win32;

namespace OutlookScraper.App.Notifications;

/// <summary>
/// Verifies — and repairs — the shell registration an unpackaged app needs before
/// Windows will show it a toast.
/// </summary>
/// <remarks>
/// Three things must exist, and <c>ToastNotificationManagerCompat</c> creates them on
/// first use:
///
/// <list type="number">
/// <item>A Start Menu shortcut carrying <c>System.AppUserModel.ID</c> and
/// <c>System.AppUserModel.ToastActivatorCLSID</c> in its property store.</item>
/// <item>A matching AUMID.</item>
/// <item>A COM activator under
/// <c>HKCU\SOFTWARE\Classes\CLSID\{guid}\LocalServer32</c>.</item>
/// </list>
///
/// <b>When the shortcut is missing, Windows silently does nothing.</b> No toast, no
/// exception, no error code — which makes it the single most common cause of "toasts
/// stopped working" and impossible to diagnose from inside the app.
///
/// Because the registration bakes in the executable's path, moving or renaming the exe
/// breaks it just as silently. This check runs at every startup for that reason, and
/// the Settings window has a "send test notification" button so the user can confirm
/// the whole path end to end.
/// </remarks>
[SupportedOSPlatform("windows")]
public static class ToastRegistration
{
    /// <summary>Must match the id the compat layer registers, and stay stable across versions.</summary>
    public const string ApplicationId = "OutlookScraper.FreeFoodWatcher";

    private const string ClassesRoot = @"SOFTWARE\Classes";

    /// <summary>
    /// Returns true when the registered executable path still matches this process.
    /// A mismatch means the app was moved and toasts will silently fail.
    /// </summary>
    public static bool IsRegistrationCurrent(out string? reason)
    {
        var currentPath = Environment.ProcessPath;

        if (string.IsNullOrEmpty(currentPath))
        {
            reason = "Could not determine the current executable path.";
            return false;
        }

        using var aumidKey = Registry.CurrentUser.OpenSubKey(
            $@"{ClassesRoot}\AppUserModelId\{ApplicationId}");

        if (aumidKey is null)
        {
            reason = "The AppUserModelId registration is missing.";
            return false;
        }

        var registeredPath = FindRegisteredServerPath();

        if (registeredPath is null)
        {
            reason = "The toast COM activator is not registered.";
            return false;
        }

        if (!registeredPath.Contains(currentPath, StringComparison.OrdinalIgnoreCase))
        {
            reason = $"Registered for '{registeredPath}' but running from '{currentPath}'. " +
                     "The application was moved or renamed.";
            return false;
        }

        reason = null;
        return true;
    }

    /// <summary>
    /// Walks the registered CLSIDs looking for a LocalServer32 pointing at this app.
    /// The activator GUID is generated by the compat layer, so it has to be found rather
    /// than assumed.
    /// </summary>
    private static string? FindRegisteredServerPath()
    {
        using var clsidRoot = Registry.CurrentUser.OpenSubKey($@"{ClassesRoot}\CLSID");

        if (clsidRoot is null)
        {
            return null;
        }

        foreach (var clsid in clsidRoot.GetSubKeyNames())
        {
            using var server = clsidRoot.OpenSubKey($@"{clsid}\LocalServer32");

            if (server?.GetValue(null) is string path &&
                path.Contains("OutlookScraper", StringComparison.OrdinalIgnoreCase))
            {
                return path;
            }
        }

        return null;
    }
}
